// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TouristSpot.API.Data;

#nullable disable

namespace TouristSpot.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260318192432_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TouristSpot.API.Models.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PontoTuristicoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PontoTuristicoId");

                    b.ToTable("Eventos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataFim = new DateTime(2026, 7, 15, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicio = new DateTime(2026, 7, 15, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Show de música ao vivo com vista panorâmica.",
                            Endereco = "Mirante Secundário",
                            Nome = "Festival de Inverno no Morro",
                            PontoTuristicoId = 1
                        },
                        new
                        {
                            Id = 2,
                            DataFim = new DateTime(2026, 8, 20, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicio = new DateTime(2026, 8, 20, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Apresentação de violino durante o crepúsculo.",
                            Endereco = "Plataforma Principal",
                            Nome = "Pôr do Sol Musical",
                            PontoTuristicoId = 1
                        },
                        new
                        {
                            Id = 3,
                            DataFim = new DateTime(2026, 5, 10, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicio = new DateTime(2026, 5, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Degustação gratuita de frutas raras de todo o Brasil.",
                            Endereco = "Ala Central",
                            Nome = "Semana das Frutas Exóticas",
                            PontoTuristicoId = 2
                        });
                });

            modelBuilder.Entity("TouristSpot.API.Models.PontoTuristico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categorias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("PontoTuristicos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categorias = "3,1",
                            Cep = "22241330",
                            Cidade = "Rio de Janeiro",
                            DataFim = new DateTime(2024, 1, 1, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicio = new DateTime(2024, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Uma das sete maravilhas do mundo moderno.",
                            Endereco = "Parque Nacional da Tijuca",
                            Estado = "RJ",
                            Nome = "Cristo Redentor"
                        },
                        new
                        {
                            Id = 2,
                            Categorias = "4",
                            Cep = "01024010",
                            Cidade = "São Paulo",
                            DataFim = new DateTime(2024, 1, 1, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicio = new DateTime(2024, 1, 1, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Ícone da gastronomia paulistana.",
                            Endereco = "Rua Cantareira, 306",
                            Estado = "SP",
                            Nome = "Mercado Municipal de SP"
                        });
                });

            modelBuilder.Entity("TouristSpot.API.Models.Evento", b =>
                {
                    b.HasOne("TouristSpot.API.Models.PontoTuristico", "PontoTuristicoPai")
                        .WithMany("EventosInternos")
                        .HasForeignKey("PontoTuristicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PontoTuristicoPai");
                });

            modelBuilder.Entity("TouristSpot.API.Models.PontoTuristico", b =>
                {
                    b.Navigation("EventosInternos");
                });
#pragma warning restore 612, 618
        }
    }
}
